### ISSUE TITLE
Checkpointing

### ISSUE THREAD

**Issue by f0uriest** [ddudt/DESC#3]
Need to save intermediate results from continuation method, also return output from all steps instead of just the last one

**Comment by ddudt** [comment]
The checkpointing needs to be updated so that it saves the boundary and pressure inputs that were being solved at that iteration, according to the `bdry_ratio` and `pres_ratio` parameters.  For instance, if the equilibrium at the current iteration was computed with `pres_ratio = 0` then the data should be saved as a vacuum solution not whatever pressure profile was input.  It might also be good to note the value of `zeta_ratio` since anything other than unity isn't really a true equilibrium.
