### ISSUE TITLE
Add option for symmetry nodes

### ISSUE THREAD

**Issue by f0uriest** [ddudt/DESC#30]
helps reduce size of the system

Also, we should think about how we're currently oversampling. If we oversample in both M and N, we've sort of double counting, so we end up with oversampling by 3x instead of 2x. Could be an improvement

**Comment by ddudt** [comment]
There is now an option for symmetric nodes, which uses the `stell_sym` input parameter.  All it does is remove the nodes with: 
(zeta > 2pi/NFP)  and also  (zeta = 0 AND theta > pi)
This reduces the total number of nodes by almost half.  Convergence appears to be worse than expected after this change. 

The "proper" symmetric node setup is more nuanced.  The number of nodes (and pattern to use) should depend on the Zernike indexing (ANSI/Fringe).  Also, the f_beta equations should not be evaluated at theta=zeta=0, since those equations are trivially satisfied.  More work will be needed on this.  

If we were doing a true spectral collocation method, we would need to oversample by at least 1.5x in both M and N.  We probably need to test to see what gives us the best convergence, which may be problem dependent.

**Comment by f0uriest** [comment]
It seems to work well for me on the Dshape tokamak, though I did have to switch to using the full (nonsymmetric) nodes for the boundary error (which i think makes sense if we're evaluating it in real space?)
I'll need to modify the FFT zernike interpolation method to work with the new node pattern. There might be some issue with only using the upper half plane at zeta=0, but keeping only zeta < pi/NFP should be fine

**Comment by ddudt** [comment]
That actually makes sense to use the full (nonsymmetric) nodes for the boundary, since we are currently evaluating the error in spectral space.  If we want to fit N Fourier coefficients we need to interpolate at at least N nodes.  However, when there is symmetry we also only need half of the boundary Fourier coefficients.  So we need to add a symmetry option in the BC function too.

**Comment by ddudt** [comment]
Added option in BC function to only use the symmetric modes.
