### ISSUE TITLE
Equilibrium solutions disagree with documentation

### ISSUE THREAD

**Issue by patil3** [ddudt/DESC#83]
### Configuration/Environment

Currently Loaded Modulefiles:

1. gmp-6.2.0
2. mpfr-4.1.0
3. mpc-1.1.0
4. isl-0.22.1
5. gcc-10.2.0/gcc-10.2.0
6. python-3.9.5

Operating System: Ubuntu 18.04.5 LTS
Kernel: Linux 4.15.0-112-generic

DESC version 0.4.3, using JAX backend, jax version=0.2.10, jaxlib version=0.1.62, dtype=float64
Using device: CPU, with 113.99 GB available memory

### Steps to reproduce the issue

Following the "Using DESC interactively" section of the documentation exactly, I tried to reproduce the same plot for "eq1". As per the steps in the given example, first, an equilibrium was obtained with elliptical boundary surface and zero pressure. Then it was perturbed to include a quadratic pressure profile. This script includes all the commands I gave:
[perturb_example1.txt](https://github.com/ddudt/DESC/files/6558432/perturb_example1.txt)
The flux surfaces I get are different than what is given in the documentation:
![flux_sf_eq1](https://user-images.githubusercontent.com/84903460/119939624-c5ffd280-bf53-11eb-9e7e-c94ef0f7362d.png)

To confirm whether this was a valid equilibrium solution, I plotted the force balance error:
![eq1_Ferror](https://user-images.githubusercontent.com/84903460/119939777-f8a9cb00-bf53-11eb-84e1-13659e78ab48.png)

It seems that perturbing the vacuum solution did not yield an equilibrium solution. However, I am not sure if a low error should be expected after perturbation.
I tried to solve this perturbed equilibrium 'eq1' using `eq1.solve(verbose=2, ftol=1e-4);`. A low error is obtained, but the flux surfaces are not the same as those in the documentation:
![eq1solved_Ferror](https://user-images.githubusercontent.com/84903460/119940289-9604ff00-bf54-11eb-87f5-c2ccb13bd249.png) ![eq1solved_fluxsf](https://user-images.githubusercontent.com/84903460/119940536-f431e200-bf54-11eb-815d-6c1a8a821234.png)

Next, I tested the high beta D-shaped tokamak example given in the cited paper. This also did not give the same equilibrium solution. I started with a vacuum solution and perturbed the pressure profile as per the profile given in the paper.
Here is my script:
[high_beta_D.txt](https://github.com/ddudt/DESC/files/6559092/high_beta_D.txt)

The perturbed flux surfaces are different that the ones in the paper. The force balance error for the perturbed equilibrium is, once again, too large:
![eq1_flux_sf](https://user-images.githubusercontent.com/84903460/119945679-66a5c080-bf5b-11eb-84ac-2bcb44a57019.png) ![eq1_Ferror](https://user-images.githubusercontent.com/84903460/119945810-8f2dba80-bf5b-11eb-9d13-dd0aa56fc220.png)

I also tried to solve for the perturbed equilibrium explicitly with `eq1.solve(verbose=2, ftol=1e-4);`,. The resulting flux surfaces do not match the ones in the paper (although the force balance error is low):
![eq1solved_flux_sf](https://user-images.githubusercontent.com/84903460/119946267-0fecb680-bf5c-11eb-954b-14cb2b312cec.png) ![eq1solved_Ferror](https://user-images.githubusercontent.com/84903460/119946676-7ffb3c80-bf5c-11eb-9e53-07945b1c3cdb.png)

I solved the same equilibrium using the command line interface and the input file provided in the repository (I changed only the maximum pressure to match the paper). I used `python3.9 -m desc -o output.out -pp -v ../DESC/examples/DESC/DSHAPE`. The input file, the flux surface plot and the force balance error plot are attached. These do not match the paper either:
[DSHAPE.txt](https://github.com/ddudt/DESC/files/6559158/DSHAPE.txt)
![flux_sf](https://user-images.githubusercontent.com/84903460/119948256-44fa0880-bf5e-11eb-9ad5-8945b656ca63.png) ![Ferror](https://user-images.githubusercontent.com/84903460/119948270-47f4f900-bf5e-11eb-99fb-4708e3632225.png)

Note: Since the solution in the paper matches the VMEC solution but the one obtained with the current DESC version does not, I thought it best to report this issue. Perhaps it is because of the recent modifications to the code since the example in documentation seems to be using "DESC version 0.3.22+40.g14b6afa.dirty". If so, and the developers are aware of it, I apologize for the inconvenience.

**Comment by dpanici** [comment]
Hi, thanks for raising the issue!

For your first point on perturbing the flux surfaces, the slight difference you see between the documentation and your local execution is something I am able to reproduce as well, so I believe that is just a product of changes made to the code slightly changing the outcome of that particular perturbation. Thanks for letting us know, we can update the docs with a more recent run of that notebook.

When you use eq.perturb, we do not expect the force balance to be zero after the perturbation, so that is expected behavior. What is being done is we are expanding the equilibrium force balance equation f(x,c)=0 in a taylor series with respect to changes in x (the state vector of flux surface positions R,Z, represented in DESC as the coefficients of the Fourier-Zernike basis) and changes in c (the other parameters needed to solve a fixed-boundary equilibrium, so pressure, iota, boundary shape, etc). We then set f(x + dx, c + dc) = 0, and find the dx needed to satisfy this equation to the specified order for the given dc (which can be a change in pressure or change from 2D to 3D boundary). Since it is basically a taylor series approximation, the perturbed equilibrium is not expected to be in perfect force balance, but it is often a good initial guess for the final equilibrium solution ( as you can see looking at the perturbed DSHAPE equilibrium you have versus the final solved equilibrium).

As for the differences in the DSHAPE equilibrium, the input file and the equilibrium in the paper were solved assuming stellarator 
up-down symmetry (in input files this is the line that reads `sym = 1`), which can be set by adding `"sym": True`  to your input dictionary in your `high_beta_D.txt` file (this is set to False by default currently when a new `Equilibrium` object is created. If you do so, you can see that the resulting solution after perturbing and then solving is similar to the VMEC solution using the below code:

```python
from desc.vmec import VMECIO # needed to load VMEC .nc files
import netCDF4 # needed for VMECIO
vmec_file = 'examples/VMEC/wout_DSHAPE.nc' # path to the VMEC DSHAPE solution
VMECIO.plot_vmec_comparison(eq1,vmec_file)
```

You can see that the two solutions have identical flux surfaces, with only slight differences in the theta contours.
![image](https://user-images.githubusercontent.com/37969854/120048745-867dc880-bfdd-11eb-99ec-9d1c2ebaf720.png)

I hope this helps, if anything else comes up don't hesitate to ask! and @f0uriest feel free to add if I missed anything

**Comment by f0uriest** [comment]
Dario covered most of it. In some cases, things will still be in equilibrium after a perturbation, but it obviously depends on the magnitude of the perturbation. The D shape example goes from beta=0 to beta=3% which is probably a bit too big to keep things in equilibrium but still should give reasonable flux surfaces by eye. I've found that in many cases stepping beta in increments of 1% produces reasonably well converged solutions with just the perturbation.

As for the symmetry issue, in theory you should get the same answer if you don't enforce symmetry explicitly (its just using more modes than necessary). We've done most of our testing with symmetry enforced, and it's possible that some recent changes to the pattern of collocation nodes don't work correctly when symmetry is not enforced. I'll look into it after the holiday.

Also as a general note, the plots in Dan's original paper were made using a very old version of the code in matlab that was mainly just a proof of concept. We've made a number of upgrades and improvements since then so we generally wouldn't expect to exactly reproduce the plots from that paper with the current version of the code (eg, note that the force error in the D shape example from the current version of the code is 1-2 orders of magnitude lower than that shown in the paper).

**Comment by f0uriest** [comment]
So one possible reason for the asymmetry you're seeing is that the full concentric grids are not up/down symmetric: 
![image](https://user-images.githubusercontent.com/22567458/120417450-d685c380-c32c-11eb-9bf7-56fd3f831e54.png)
When symmetry is explicitly enforced, we only use the nodes from the top half (0<theta<pi) but for nonsymmetric cases we use the full grid.

Not sure if this is "wrong" per say, as generally if the solution is symmetric it should be imposed explicitly, though I could see an argument that the grid used for non-symmetric cases should still be symmetric. Not sure the best way to do that though, the concentric grids are a bit tricky.

@ddudt thoughts?

**Comment by ddudt** [comment]
I agree the grid is a likely source of this problem.  The concentric grid used to be up/down symmetric, with some nodes at theta=0.  However, when stellarator symmetry is enforced, that grid resulted in some of the force balance equations being linearly dependent.  To avoid that issue we introduced a phase shift in the theta coordinate, giving the grid pictured above which is not up/down symmetric.  

If I remember correctly, this change to the grid was made after the original example in the documentation.  That would help explain why the latest version of the code no longer reproduces that example exactly.  

The linear independence of the force balance equations is only an issue with stellarator symmetry (in general the force error should not have any symmetric structure).  Therefore the "full" (non-symmetric) concentric grid does not need the phase shift in the theta coordinates.  @f0uriest we should probably only add the phase shift for symmetric grids.

**Comment by f0uriest** [comment]
OK, making that change seems to help somewhat but doesn't eliminate the asymmetry entirely. I think another possible source is the SVD of the jacobian that's done in the newton method. If the true solution is symmetric but not enforced, and the grid is symmetric, then half the equations will be linearly dependent, so they get removed by the truncated SVD. However, which ones get removed is non-deterministic, and would likely vary each iteration, so there's no guarantee that it will always use the top half or bottom half or some mix of linearly independent equations, so effectively its using a non-symmetric grid.

Closing this for now, because I think the "correct" solution is just to explicitly enforce symmetry when its desired, but feel free to reopen if its still an issue
